# Generated by Django 5.1.1 on 2024-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='', upload_to='users/doctors/image'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='specialist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User'), (3, 'Doctor')]),
        ),
    ]
