# Generated by Django 5.1.1 on 2024-10-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_users_image_users_name_users_specialist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('specialist', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='users/doctors/image')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='specialist',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User')]),
        ),
    ]
