# Generated by Django 5.1.1 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_doctors_remove_users_image_remove_users_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_no', models.CharField(max_length=12)),
                ('residence', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
